package com.example.final_nextstop.util

object CapitalResolver {
    val countryToCapital = mapOf(
        "Afghanistan" to "Kabul",
        "Albania" to "Tirana",
        "Algeria" to "Algiers",
        "American Samoa" to "Pago Pago",
        "Andorra" to "Andorra la Vella",
        "Angola" to "Luanda",
        "Anguilla" to "The Valley",
        "Antigua & Barbuda" to "Saint John's",
        "Argentina" to "Buenos Aires",
        "Armenia" to "Yerevan",
        "Aruba" to "Oranjestad",
        "Australia" to "Canberra",
        "Austria" to "Vienna",
        "Azerbaijan" to "Baku",
        "Bahamas" to "Nassau",
        "Bahrain" to "Manama",
        "Bangladesh" to "Dhaka",
        "Barbados" to "Bridgetown",
        "Belarus" to "Minsk",
        "Belgium" to "Brussels",
        "Belize" to "Belmopan",
        "Benin" to "Porto-Novo",
        "Bermuda" to "Hamilton",
        "Bhutan" to "Thimphu",
        "Bolivia" to "Sucre",
        "Bosnia & Herzegovina" to "Sarajevo",
        "Botswana" to "Gaborone",
        "Brazil" to "Brasília",
        "British Indian Ocean Territory" to "Diego Garcia",
        "British Virgin Islands" to "Road Town",
        "Brunei" to "Bandar Seri Begawan",
        "Bulgaria" to "Sofia",
        "Burkina Faso" to "Ouagadougou",
        "Burundi" to "Gitega",
        "Cambodia" to "Phnom Penh",
        "Cameroon" to "Yaoundé",
        "Canada" to "Ottawa",
        "Canary Islands" to "Santa Cruz de Tenerife",
        "Cape Verde" to "Praia",
        "Caribbean Netherlands" to "Kralendijk",
        "Cayman Islands" to "George Town",
        "Central African Republic" to "Bangui",
        "Ceuta & Melilla" to "Ceuta",
        "Chad" to "N'Djamena",
        "Chile" to "Santiago",
        "China" to "Beijing",
        "Christmas Island" to "Flying Fish Cove",
        "Cocos (Keeling) Islands" to "West Island",
        "Colombia" to "Bogotá",
        "Comoros" to "Moroni",
        "Congo - Brazzaville" to "Brazzaville",
        "Congo - Kinshasa" to "Kinshasa",
        "Cook Islands" to "Avarua",
        "Costa Rica" to "San José",
        "Croatia" to "Zagreb",
        "Cuba" to "Havana",
        "Curaçao" to "Willemstad",
        "Cyprus" to "Nicosia",
        "Czechia" to "Prague",
        "Côte d’Ivoire" to "Yamoussoukro",
        "Denmark" to "Copenhagen",
        "Diego Garcia" to "Camp Justice",
        "Djibouti" to "Djibouti",
        "Dominica" to "Roseau",
        "Dominican Republic" to "Santo Domingo",
        "Ecuador" to "Quito",
        "Egypt" to "Cairo",
        "El Salvador" to "San Salvador",
        "Equatorial Guinea" to "Malabo",
        "Eritrea" to "Asmara",
        "Estonia" to "Tallinn",
        "Eswatini" to "Mbabane",
        "Ethiopia" to "Addis Ababa",
        "Europe" to "Brussels",
        "Falkland Islands (Islas Malvinas)" to "Stanley",
        "Faroe Islands" to "Tórshavn",
        "Fiji" to "Suva",
        "Finland" to "Helsinki",
        "France" to "Paris",
        "French Guiana" to "Cayenne",
        "French Polynesia" to "Papeete",
        "Gabon" to "Libreville",
        "Gambia" to "Banjul",
        "Georgia" to "Tbilisi",
        "Germany" to "Berlin",
        "Ghana" to "Accra",
        "Gibraltar" to "Gibraltar",
        "Greece" to "Athens",
        "Greenland" to "Nuuk",
        "Grenada" to "St. George's",
        "Guadeloupe" to "Basse-Terre",
        "Guam" to "Hagåtña",
        "Guatemala" to "Guatemala City",
        "Guernsey" to "St. Peter Port",
        "Guinea" to "Conakry",
        "Guinea-Bissau" to "Bissau",
        "Guyana" to "Georgetown",
        "Haiti" to "Port-au-Prince",
        "Honduras" to "Tegucigalpa",
        "Hong Kong" to "Hong Kong",
        "Hungary" to "Budapest",
        "Iceland" to "Reykjavik",
        "India" to "New Delhi",
        "Indonesia" to "Jakarta",
        "Iran" to "Tehran",
        "Iraq" to "Baghdad",
        "Ireland" to "Dublin",
        "Isle of Man" to "Douglas",
        "Israel" to "Jerusalem",
        "Italy" to "Rome",
        "Jamaica" to "Kingston",
        "Japan" to "Tokyo",
        "Jersey" to "Saint Helier",
        "Jordan" to "Amman",
        "Kazakhstan" to "Astana",
        "Kenya" to "Nairobi",
        "Kiribati" to "Tarawa",
        "Kosovo" to "Pristina",
        "Kuwait" to "Kuwait City",
        "Kyrgyzstan" to "Bishkek",
        "Laos" to "Vientiane",
        "Latin America" to "Mexico City",
        "Latvia" to "Riga",
        "Lebanon" to "Beirut",
        "Lesotho" to "Maseru",
        "Liberia" to "Monrovia",
        "Libya" to "Tripoli",
        "Liechtenstein" to "Vaduz",
        "Lithuania" to "Vilnius",
        "Luxembourg" to "Luxembourg",
        "Macao" to "Macau",
        "Madagascar" to "Antananarivo",
        "Malawi" to "Lilongwe",
        "Malaysia" to "Kuala Lumpur",
        "Maldives" to "Malé",
        "Mali" to "Bamako",
        "Malta" to "Valletta",
        "Marshall Islands" to "Majuro",
        "Martinique" to "Fort-de-France",
        "Mauritania" to "Nouakchott",
        "Mauritius" to "Port Louis",
        "Mayotte" to "Mamoudzou",
        "Mexico" to "Mexico City",
        "Micronesia" to "Palikir",
        "Moldova" to "Chișinău",
        "Monaco" to "Monaco",
        "Mongolia" to "Ulaanbaatar",
        "Montenegro" to "Podgorica",
        "Montserrat" to "Plymouth",
        "Morocco" to "Rabat",
        "Mozambique" to "Maputo",
        "Myanmar (Burma)" to "Naypyidaw",
        "Namibia" to "Windhoek",
        "Nauru" to "Yaren",
        "Nepal" to "Kathmandu",
        "Netherlands" to "Amsterdam",
        "New Caledonia" to "Nouméa",
        "New Zealand" to "Wellington",
        "Nicaragua" to "Managua",
        "Niger" to "Niamey",
        "Nigeria" to "Abuja",
        "Niue" to "Alofi",
        "Norfolk Island" to "Kingston",
        "North Korea" to "Pyongyang",
        "North Macedonia" to "Skopje",
        "Northern Mariana Islands" to "Saipan",
        "Norway" to "Oslo",
        "Oman" to "Muscat",
        "Pakistan" to "Islamabad",
        "Palau" to "Ngerulmud",
        "Palestine" to "Ramallah",
        "Panama" to "Panama City",
        "Papua New Guinea" to "Port Moresby",
        "Paraguay" to "Asunción",
        "Peru" to "Lima",
        "Philippines" to "Manila",
        "Pitcairn Islands" to "Adamstown",
        "Poland" to "Warsaw",
        "Portugal" to "Lisbon",
        "Pseudo-Accents" to "N/A",
        "Pseudo-Bidi" to "N/A",
        "Puerto Rico" to "San Juan",
        "Qatar" to "Doha",
        "Romania" to "Bucharest",
        "Russia" to "Moscow",
        "Rwanda" to "Kigali",
        "Réunion" to "Saint-Denis",
        "Samoa" to "Apia",
        "San Marino" to "San Marino",
        "Saudi Arabia" to "Riyadh",
        "Senegal" to "Dakar",
        "Serbia" to "Belgrade",
        "Seychelles" to "Victoria",
        "Sierra Leone" to "Freetown",
        "Singapore" to "Singapore",
        "Sint Maarten" to "Philipsburg",
        "Slovakia" to "Bratislava",
        "Slovenia" to "Ljubljana",
        "Solomon Islands" to "Honiara",
        "Somalia" to "Mogadishu",
        "South Africa" to "Pretoria",
        "South Korea" to "Seoul",
        "South Sudan" to "Juba",
        "Spain" to "Madrid",
        "Sri Lanka" to "Sri Jayawardenepura Kotte",
        "St. Barthélemy" to "Gustavia",
        "St. Helena" to "Jamestown",
        "St. Kitts & Nevis" to "Basseterre",
        "St. Lucia" to "Castries",
        "St. Martin" to "Marigot",
        "St. Pierre & Miquelon" to "Saint-Pierre",
        "St. Vincent & Grenadines" to "Kingstown",
        "Sudan" to "Khartoum",
        "Suriname" to "Paramaribo",
        "Svalbard & Jan Mayen" to "Longyearbyen",
        "Sweden" to "Stockholm",
        "Switzerland" to "Bern",
        "Syria" to "Damascus",
        "São Tomé & Príncipe" to "São Tomé",
        "Taiwan" to "Taipei",
        "Tajikistan" to "Dushanbe",
        "Tanzania" to "Dodoma",
        "Thailand" to "Bangkok",
        "Timor-Leste" to "Dili",
        "Togo" to "Lomé",
        "Tokelau" to "Nukunonu",
        "Tonga" to "Nukuʻalofa",
        "Trinidad & Tobago" to "Port of Spain",
        "Tunisia" to "Tunis",
        "Turkmenistan" to "Ashgabat",
        "Turks & Caicos Islands" to "Cockburn Town",
        "Tuvalu" to "Funafuti",
        "Türkiye" to "Ankara",
        "U.S. Outlying Islands" to "Washington, D.C.",
        "U.S. Virgin Islands" to "Charlotte Amalie",
        "Uganda" to "Kampala",
        "Ukraine" to "Kyiv",
        "United Arab Emirates" to "Abu Dhabi",
        "United Kingdom" to "London",
        "United States" to "Washington, D.C.",
        "Uruguay" to "Montevideo",
        "Uzbekistan" to "Tashkent",
        "Vanuatu" to "Port Vila",
        "Vatican City" to "Vatican City",
        "Venezuela" to "Caracas",
        "Vietnam" to "Hanoi",
        "Wallis & Futuna" to "Mata-Utu",
        "Western Sahara" to "Laayoune",
        "Yemen" to "Sana'a",
        "Zambia" to "Lusaka",
        "Zimbabwe" to "Harare",
        "world" to "Earth",
        "Åland Islands" to "Mariehamn"
    )

    fun getCapitalForCountry(country: String): String? {
        return countryToCapital[country]
    }

    fun getCountryForCapital(capital: String): String? {
        return countryToCapital.entries.find { it.value.equals(capital, ignoreCase = true) }?.key
    }

}