package com.example.final_nextstop.util

object CapitalResolver {
    val countryToCapitalInEnglish = mapOf(
        "Afghanistan" to "Kabul",
        "Albania" to "Tirana",
        "Algeria" to "Algiers",
        "American Samoa" to "Pago Pago",
        "Andorra" to "Andorra la Vella",
        "Angola" to "Luanda",
        "Anguilla" to "The Valley",
        "Antigua & Barbuda" to "Saint John's",
        "Argentina" to "Buenos Aires",
        "Armenia" to "Yerevan",
        "Aruba" to "Oranjestad",
        "Australia" to "Canberra",
        "Austria" to "Vienna",
        "Azerbaijan" to "Baku",
        "Bahamas" to "Nassau",
        "Bahrain" to "Manama",
        "Bangladesh" to "Dhaka",
        "Barbados" to "Bridgetown",
        "Belarus" to "Minsk",
        "Belgium" to "Brussels",
        "Belize" to "Belmopan",
        "Benin" to "Porto-Novo",
        "Bermuda" to "Hamilton",
        "Bhutan" to "Thimphu",
        "Bolivia" to "Sucre",
        "Bosnia & Herzegovina" to "Sarajevo",
        "Botswana" to "Gaborone",
        "Brazil" to "Brasília",
        "British Indian Ocean Territory" to "Diego Garcia",
        "British Virgin Islands" to "Road Town",
        "Brunei" to "Bandar Seri Begawan",
        "Bulgaria" to "Sofia",
        "Burkina Faso" to "Ouagadougou",
        "Burundi" to "Gitega",
        "Cambodia" to "Phnom Penh",
        "Cameroon" to "Yaoundé",
        "Canada" to "Ottawa",
        "Canary Islands" to "Santa Cruz de Tenerife",
        "Cape Verde" to "Praia",
        "Caribbean Netherlands" to "Kralendijk",
        "Cayman Islands" to "George Town",
        "Central African Republic" to "Bangui",
        "Ceuta & Melilla" to "Ceuta",
        "Chad" to "N'Djamena",
        "Chile" to "Santiago",
        "China" to "Beijing",
        "Christmas Island" to "Flying Fish Cove",
        "Cocos (Keeling) Islands" to "West Island",
        "Colombia" to "Bogotá",
        "Comoros" to "Moroni",
        "Congo - Brazzaville" to "Brazzaville",
        "Congo - Kinshasa" to "Kinshasa",
        "Cook Islands" to "Avarua",
        "Costa Rica" to "San José",
        "Croatia" to "Zagreb",
        "Cuba" to "Havana",
        "Curaçao" to "Willemstad",
        "Cyprus" to "Nicosia",
        "Czechia" to "Prague",
        "Côte d’Ivoire" to "Yamoussoukro",
        "Denmark" to "Copenhagen",
        "Diego Garcia" to "Camp Justice",
        "Djibouti" to "Djibouti",
        "Dominica" to "Roseau",
        "Dominican Republic" to "Santo Domingo",
        "Ecuador" to "Quito",
        "Egypt" to "Cairo",
        "El Salvador" to "San Salvador",
        "Equatorial Guinea" to "Malabo",
        "Eritrea" to "Asmara",
        "Estonia" to "Tallinn",
        "Eswatini" to "Mbabane",
        "Ethiopia" to "Addis Ababa",
        "Europe" to "Brussels",
        "Falkland Islands (Islas Malvinas)" to "Stanley",
        "Faroe Islands" to "Tórshavn",
        "Fiji" to "Suva",
        "Finland" to "Helsinki",
        "France" to "Paris",
        "French Guiana" to "Cayenne",
        "French Polynesia" to "Papeete",
        "Gabon" to "Libreville",
        "Gambia" to "Banjul",
        "Georgia" to "Tbilisi",
        "Germany" to "Berlin",
        "Ghana" to "Accra",
        "Gibraltar" to "Gibraltar",
        "Greece" to "Athens",
        "Greenland" to "Nuuk",
        "Grenada" to "St. George's",
        "Guadeloupe" to "Basse-Terre",
        "Guam" to "Hagåtña",
        "Guatemala" to "Guatemala City",
        "Guernsey" to "St. Peter Port",
        "Guinea" to "Conakry",
        "Guinea-Bissau" to "Bissau",
        "Guyana" to "Georgetown",
        "Haiti" to "Port-au-Prince",
        "Honduras" to "Tegucigalpa",
        "Hong Kong" to "Hong Kong",
        "Hungary" to "Budapest",
        "Iceland" to "Reykjavik",
        "India" to "New Delhi",
        "Indonesia" to "Jakarta",
        "Iran" to "Tehran",
        "Iraq" to "Baghdad",
        "Ireland" to "Dublin",
        "Isle of Man" to "Douglas",
        "Israel" to "Jerusalem",
        "Italy" to "Rome",
        "Jamaica" to "Kingston",
        "Japan" to "Tokyo",
        "Jersey" to "Saint Helier",
        "Jordan" to "Amman",
        "Kazakhstan" to "Astana",
        "Kenya" to "Nairobi",
        "Kiribati" to "Tarawa",
        "Kosovo" to "Pristina",
        "Kuwait" to "Kuwait City",
        "Kyrgyzstan" to "Bishkek",
        "Laos" to "Vientiane",
        "Latin America" to "Mexico City",
        "Latvia" to "Riga",
        "Lebanon" to "Beirut",
        "Lesotho" to "Maseru",
        "Liberia" to "Monrovia",
        "Libya" to "Tripoli",
        "Liechtenstein" to "Vaduz",
        "Lithuania" to "Vilnius",
        "Luxembourg" to "Luxembourg",
        "Macao" to "Macau",
        "Madagascar" to "Antananarivo",
        "Malawi" to "Lilongwe",
        "Malaysia" to "Kuala Lumpur",
        "Maldives" to "Malé",
        "Mali" to "Bamako",
        "Malta" to "Valletta",
        "Marshall Islands" to "Majuro",
        "Martinique" to "Fort-de-France",
        "Mauritania" to "Nouakchott",
        "Mauritius" to "Port Louis",
        "Mayotte" to "Mamoudzou",
        "Mexico" to "Mexico City",
        "Micronesia" to "Palikir",
        "Moldova" to "Chișinău",
        "Monaco" to "Monaco",
        "Mongolia" to "Ulaanbaatar",
        "Montenegro" to "Podgorica",
        "Montserrat" to "Plymouth",
        "Morocco" to "Rabat",
        "Mozambique" to "Maputo",
        "Myanmar (Burma)" to "Naypyidaw",
        "Namibia" to "Windhoek",
        "Nauru" to "Yaren",
        "Nepal" to "Kathmandu",
        "Netherlands" to "Amsterdam",
        "New Caledonia" to "Nouméa",
        "New Zealand" to "Wellington",
        "Nicaragua" to "Managua",
        "Niger" to "Niamey",
        "Nigeria" to "Abuja",
        "Niue" to "Alofi",
        "Norfolk Island" to "Kingston",
        "North Korea" to "Pyongyang",
        "North Macedonia" to "Skopje",
        "Northern Mariana Islands" to "Saipan",
        "Norway" to "Oslo",
        "Oman" to "Muscat",
        "Pakistan" to "Islamabad",
        "Palau" to "Ngerulmud",
        "Palestine" to "Ramallah",
        "Panama" to "Panama City",
        "Papua New Guinea" to "Port Moresby",
        "Paraguay" to "Asunción",
        "Peru" to "Lima",
        "Philippines" to "Manila",
        "Pitcairn Islands" to "Adamstown",
        "Poland" to "Warsaw",
        "Portugal" to "Lisbon",
        "Pseudo-Accents" to "N/A",
        "Pseudo-Bidi" to "N/A",
        "Puerto Rico" to "San Juan",
        "Qatar" to "Doha",
        "Romania" to "Bucharest",
        "Russia" to "Moscow",
        "Rwanda" to "Kigali",
        "Réunion" to "Saint-Denis",
        "Samoa" to "Apia",
        "San Marino" to "San Marino",
        "Saudi Arabia" to "Riyadh",
        "Senegal" to "Dakar",
        "Serbia" to "Belgrade",
        "Seychelles" to "Victoria",
        "Sierra Leone" to "Freetown",
        "Singapore" to "Singapore",
        "Sint Maarten" to "Philipsburg",
        "Slovakia" to "Bratislava",
        "Slovenia" to "Ljubljana",
        "Solomon Islands" to "Honiara",
        "Somalia" to "Mogadishu",
        "South Africa" to "Pretoria",
        "South Korea" to "Seoul",
        "South Sudan" to "Juba",
        "Spain" to "Madrid",
        "Sri Lanka" to "Sri Jayawardenepura Kotte",
        "St. Barthélemy" to "Gustavia",
        "St. Helena" to "Jamestown",
        "St. Kitts & Nevis" to "Basseterre",
        "St. Lucia" to "Castries",
        "St. Martin" to "Marigot",
        "St. Pierre & Miquelon" to "Saint-Pierre",
        "St. Vincent & Grenadines" to "Kingstown",
        "Sudan" to "Khartoum",
        "Suriname" to "Paramaribo",
        "Svalbard & Jan Mayen" to "Longyearbyen",
        "Sweden" to "Stockholm",
        "Switzerland" to "Bern",
        "Syria" to "Damascus",
        "São Tomé & Príncipe" to "São Tomé",
        "Taiwan" to "Taipei",
        "Tajikistan" to "Dushanbe",
        "Tanzania" to "Dodoma",
        "Thailand" to "Bangkok",
        "Timor-Leste" to "Dili",
        "Togo" to "Lomé",
        "Tokelau" to "Nukunonu",
        "Tonga" to "Nukuʻalofa",
        "Trinidad & Tobago" to "Port of Spain",
        "Tunisia" to "Tunis",
        "Turkmenistan" to "Ashgabat",
        "Turks & Caicos Islands" to "Cockburn Town",
        "Tuvalu" to "Funafuti",
        "Türkiye" to "Ankara",
        "U.S. Outlying Islands" to "Washington, D.C.",
        "U.S. Virgin Islands" to "Charlotte Amalie",
        "Uganda" to "Kampala",
        "Ukraine" to "Kyiv",
        "United Arab Emirates" to "Abu Dhabi",
        "United Kingdom" to "London",
        "United States" to "Washington, D.C.",
        "Uruguay" to "Montevideo",
        "Uzbekistan" to "Tashkent",
        "Vanuatu" to "Port Vila",
        "Vatican City" to "Vatican City",
        "Venezuela" to "Caracas",
        "Vietnam" to "Hanoi",
        "Wallis & Futuna" to "Mata-Utu",
        "Western Sahara" to "Laayoune",
        "Yemen" to "Sana'a",
        "Zambia" to "Lusaka",
        "Zimbabwe" to "Harare",
        "world" to "Earth",
        "Åland Islands" to "Mariehamn"
    )
        //////////////////////////

    val countryToCapitalInHebrew = mapOf(
        "אפגניסטן" to "Kabul",
        "אלבניה" to "Tirana",
        "אלג׳יריה" to "Algiers",
        "סמואה האמריקנית" to "Pago Pago",
        "אנדורה" to "Andorra la Vella",
        "אנגולה" to "Luanda",
        "אנגווילה" to "The Valley",
        "אנטיגואה וברבודה" to "Saint John's",
        "ארגנטינה" to "Buenos Aires",
        "ארמניה" to "Yerevan",
        "ארובה" to "Oranjestad",
        "אוסטרליה" to "Canberra",
        "אוסטריה" to "Vienna",
        "אזרבייג׳ן" to "Baku",
        "בהאמה" to "Nassau",
        "בחריין" to "Manama",
        "בנגלדש" to "Dhaka",
        "ברבדוס" to "Bridgetown",
        "בלארוס" to "Minsk",
        "בלגיה" to "Brussels",
        "בליז" to "Belmopan",
        "בנין" to "Porto-Novo",
        "ברמודה" to "Hamilton",
        "בהוטן" to "Thimphu",
        "בוליביה" to "Sucre",
        "בוסניה והרצגובינה" to "Sarajevo",
        "בוצואנה" to "Gaborone",
        "ברזיל" to "Brasília",
        "הטריטוריה הבריטית באוקיינוס ההודי" to "Diego Garcia",
        "האיים הבתוליים הבריטיים" to "Road Town",
        "ברוניי" to "Bandar Seri Begawan",
        "בולגריה" to "Sofia",
        "בורקינה פאסו" to "Ouagadougou",
        "בורונדי" to "Gitega",
        "קמבודיה" to "Phnom Penh",
        "קמרון" to "Yaoundé",
        "קנדה" to "Ottawa",
        "האיים הקנריים" to "Santa Cruz de Tenerife",
        "כף ורדה" to "Praia",
        "האיים הקריביים ההולנדיים" to "Kralendijk",
        "איי קיימן" to "George Town",
        "הרפובליקה המרכז-אפריקאית" to "Bangui",
        "סאוטה ומלייה" to "Ceuta",
        "צ׳אד" to "N'Djamena",
        "צ׳ילה" to "Santiago",
        "סין" to "Beijing",
        "אי חג המולד" to "Flying Fish Cove",
        "איי קוקוס (קילינג)" to "West Island",
        "קולומביה" to "Bogotá",
        "קומורו" to "Moroni",
        "קונגו - ברזאויל" to "Brazzaville",
        "קונגו - קינשאסה" to "Kinshasa",
        "איי קוק" to "Avarua",
        "קוסטה ריקה" to "San José",
        "קרואטיה" to "Zagreb",
        "קובה" to "Havana",
        "קוראסאו" to "Willemstad",
        "קפריסין" to "Nicosia",
        "צ׳כיה" to "Prague",
        "חוף השנהב" to "Yamoussoukro",
        "דנמרק" to "Copenhagen",
        "דייגו גרסיה" to "Camp Justice",
        "ג׳יבוטי" to "Djibouti",
        "דומיניקה" to "Roseau",
        "הרפובליקה הדומיניקנית" to "Santo Domingo",
        "אקוודור" to "Quito",
        "מצרים" to "Cairo",
        "אל סלבדור" to "San Salvador",
        "גיניאה המשוונית" to "Malabo",
        "אריתריאה" to "Asmara",
        "אסטוניה" to "Tallinn",
        "אסוואטיני" to "Mbabane",
        "אתיופיה" to "Addis Ababa",
        "אירופה" to "Brussels",
        "איי פוקלנד (איסלאס מלווינס)" to "Stanley",
        "איי פארו" to "Tórshavn",
        "פיג׳י" to "Suva",
        "פינלנד" to "Helsinki",
        "צרפת" to "Paris",
        "גיאנה הצרפתית" to "Cayenne",
        "פולינזיה הצרפתית" to "Papeete",
        "גבון" to "Libreville",
        "גמביה" to "Banjul",
        "גאורגיה" to "Tbilisi",
        "גרמניה" to "Berlin",
        "גאנה" to "Accra",
        "גיברלטר" to "Gibraltar",
        "יוון" to "Athens",
        "גרינלנד" to "Nuuk",
        "גרנדה" to "St. George's",
        "גוואדלופ" to "Basse-Terre",
        "גואם" to "Hagåtña",
        "גואטמלה" to "Guatemala City",
        "גרנזי" to "St. Peter Port",
        "גיניאה" to "Conakry",
        "גיניאה ביסאו" to "Bissau",
        "גיאנה" to "Georgetown",
        "האיטי" to "Port-au-Prince",
        "הונדורס" to "Tegucigalpa",
        "הונג קונג" to "Hong Kong",
        "הונגריה" to "Budapest",
        "איסלנד" to "Reykjavik",
        "הודו" to "New Delhi",
        "אינדונזיה" to "Jakarta",
        "איראן" to "Tehran",
        "עיראק" to "Baghdad",
        "אירלנד" to "Dublin",
        "האי מאן" to "Douglas",
        "ישראל" to "Jerusalem",
        "איטליה" to "Rome",
        "ג׳מייקה" to "Kingston",
        "יפן" to "Tokyo",
        "ג׳רזי" to "Saint Helier",
        "ירדן" to "Amman",
        "קזחסטן" to "Astana",
        "קניה" to "Nairobi",
        "קיריבאטי" to "Tarawa",
        "קוסובו" to "Pristina",
        "כווית" to "Kuwait City",
        "קירגיזסטן" to "Bishkek",
        "לאוס" to "Vientiane",
        "אמריקה הלטינית" to "Mexico City",
        "לטביה" to "Riga",
        "לבנון" to "Beirut",
        "לסוטו" to "Maseru",
        "ליבריה" to "Monrovia",
        "לוב" to "Tripoli",
        "ליכטנשטיין" to "Vaduz",
        "ליטא" to "Vilnius",
        "לוקסמבורג" to "Luxembourg",
        "מקאו" to "Macau",
        "מדגסקר" to "Antananarivo",
        "מלאווי" to "Lilongwe",
        "מלזיה" to "Kuala Lumpur",
        "מלדיבים" to "Malé",
        "מאלי" to "Bamako",
        "מלטה" to "Valletta",
        "איי מרשל" to "Majuro",
        "מרטיניק" to "Fort-de-France",
        "מאוריטניה" to "Nouakchott",
        "מאוריציוס" to "Port Louis",
        "מאיוט" to "Mamoudzou",
        "מקסיקו" to "Mexico City",
        "מיקרונזיה" to "Palikir",
        "מולדובה" to "Chișinău",
        "מונקו" to "Monaco",
        "מונגוליה" to "Ulaanbaatar",
        "מונטנגרו" to "Podgorica",
        "מונסראט" to "Plymouth",
        "מרוקו" to "Rabat",
        "מוזמביק" to "Maputo",
        "מיאנמר (בורמה)" to "Naypyidaw",
        "נמיביה" to "Windhoek",
        "נאורו" to "Yaren",
        "נפאל" to "Kathmandu",
        "הולנד" to "Amsterdam",
        "קלדוניה החדשה" to "Nouméa",
        "ניו זילנד" to "Wellington",
        "ניקרגואה" to "Managua",
        "ניז׳ר" to "Niamey",
        "ניגריה" to "Abuja",
        "ניווה" to "Alofi",
        "איי נורפולק" to "Kingston",
        "קוריאה הצפונית" to "Pyongyang",
        "קוריאה הדרומית" to "Seoul",
        "מקדוניה הצפונית" to "Skopje",
        "איי מריאנה הצפוניים" to "Saipan",
        "נורווגיה" to "Oslo",
        "עומאן" to "Muscat",
        "פקיסטן" to "Islamabad",
        "פלאו" to "Ngerulmud",
        "פלסטין" to "Ramallah",
        "פנמה" to "Panama City",
        "פפואה גינאה החדשה" to "Port Moresby",
        "פרגוואי" to "Asunción",
        "פרו" to "Lima",
        "פיליפינים" to "Manila",
        "איי פיטקרן" to "Adamstown",
        "פולין" to "Warsaw",
        "פורטוגל" to "Lisbon",
        "פוארטו ריקו" to "San Juan",
        "קטאר" to "Doha",
        "רומניה" to "Bucharest",
        "רוסיה" to "Moscow",
        "רואנדה" to "Kigali",
        "ראוניון" to "Saint-Denis",
        "סמואה" to "Apia",
        "סן מרטן" to "San Marino",
        "סן מרינו" to "San Marino",
        "ערב הסעודית" to "Riyadh",
        "סנגל" to "Dakar",
        "סרביה" to "Belgrade",
        "סיישל" to "Victoria",
        "סיירה לאונה" to "Freetown",
        "סינגפור" to "Singapore",
        "סנט מארטן" to "Philipsburg",
        "סלובקיה" to "Bratislava",
        "סלובניה" to "Ljubljana",
        "איי שלמה" to "Honiara",
        "סומליה" to "Mogadishu",
        "דרום אפריקה" to "Pretoria",
        "דרום קוריאה" to "Seoul",
        "דרום סודן" to "Juba",
        "ספרד" to "Madrid",
        "סרי לנקה" to "Sri Jayawardenepura Kotte",
        "סנט ברתולומיאו" to "Gustavia",
        "סנט הלנה" to "Jamestown",
        "סנט קיטס ונוויס" to "Basseterre",
        "סנט לוסיה" to "Castries",
        "סן מרטן" to "Marigot",
        "סנט פייר ומיקלון" to "Saint-Pierre",
        "סנט וינסנט והגרנדינים" to "Kingstown",
        "סודן" to "Khartoum",
        "סורינאם" to "Paramaribo",
        "סבאלברד ויאן מאיין" to "Longyearbyen",
        "שוודיה" to "Stockholm",
        "שווייץ" to "Bern",
        "סוריה" to "Damascus",
        "סאו טומה ופרינסיפה" to "São Tomé",
        "טייוואן" to "Taipei",
        "טג׳יקיסטן" to "Dushanbe",
        "טנזניה" to "Dodoma",
        "תאילנד" to "Bangkok",
        "טימור-לסטה" to "Dili",
        "טוגו" to "Lomé",
        "טוקלאו" to "Nukunonu",
        "טונגה" to "Nukuʻalofa",
        "טרינידד וטובגו" to "Port of Spain",
        "תוניסיה" to "Tunis",
        "טורקמניסטן" to "Ashgabat",
        "איי טרקס וקייקוס" to "Cockburn Town",
        "טובאלו" to "Funafuti",
        "טורקיה" to "Ankara",
        "האיים המרוחקים הקטנים של ארה\"ב" to "Washington, D.C.",
        "איי הבתולה של ארצות הברית" to "Charlotte Amalie",
        "אוגנדה" to "Kampala",
        "אוקראינה" to "Kyiv",
        "איחוד האמירויות" to "Abu Dhabi",
        "הממלכה המאוחדת" to "London",
        "ארצות הברית" to "Washington, D.C.",
        "אורוגוואי" to "Montevideo",
        "אוזבקיסטן" to "Tashkent",
        "ונואטו" to "Port Vila",
        "הוותיקן" to "Vatican City",
        "ונצואלה" to "Caracas",
        "וייטנאם" to "Hanoi",
        "איי ווליס ופוטונה" to "Mata-Utu",
        "סהרה המערבית" to "Laayoune",
        "תימן" to "Sana'a",
        "זמביה" to "Lusaka",
        "זימבבואה" to "Harare",
        "העולם" to "Earth",
        "איי אלנד" to "Mariehamn"
    )

    fun getCapitalFromCountryInEnglish(country: String): String? {
        return countryToCapitalInEnglish[country]
    }

    fun getCapitalFromCountryInHebrew(country: String): String? {
        return countryToCapitalInHebrew[country]
    }

    fun getCountryFromCapitalInEnglish(capital: String): String? {
        return countryToCapitalInEnglish.entries.find { it.value.equals(capital, ignoreCase = true) }?.key
    }

    fun getCountryFromCapitalInHebrew(capital: String): String? {
        return countryToCapitalInHebrew.entries.find { it.value.equals(capital, ignoreCase = true) }?.key
    }

}